name: Build Majora iOS
on: 
  push:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4
        with:
          repository: Francessco121/Zelda64Recomp
          submodules: recursive
          fetch-depth: 1

      - name: Configurar Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Instalar Dependencias del Sistema
        run: |
          brew install cmake ninja freetype pkg-config

      - name: Descargar y Preparar SDL2 para iOS
        run: |
          git clone https://github.com/libsdl-org/SDL.git -b SDL2
          cd SDL
          mkdir build-ios
          cd build-ios
          cmake .. -G Ninja \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_INSTALL_PREFIX=../../sdl2_ios \
            -DSDL_STATIC=ON \
            -DSDL_SHARED=OFF
          ninja install

      - name: Configurar Proyecto para iOS
        run: |
          mkdir build
          cd build
          FREETYPE_PATH=$(brew --prefix freetype)
          
          mkdir -p ../rsp
          touch ../rsp/aspMain.cpp
          echo "void dummy() {}" > ../recompiled_funcs.cpp

          cmake .. -G Ninja \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DSDL2_DIR=$GITHUB_WORKSPACE/sdl2_ios/lib/cmake/SDL2 \
            -DFREETYPE_INCLUDE_DIRS=$FREETYPE_PATH/include/freetype2 \
            -DFREETYPE_LIBRARY=$FREETYPE_PATH/lib/libfreetype.a \
            -DRECOMP_PLATFORM=iOS \
            -DUSE_OPENGL=OFF \
            -DUSE_VULKAN=OFF \
            -DUSE_METAL=ON \
            -DNFD_PORTABLE=OFF \
            -DNFD_GTK=OFF \
            -DNFD_MACOS=OFF
            
      - name: Compilar
        run: |
          cd build
          ninja
